name: Agda-Unimath CI
on:
  # To run this workflow manually
  workflow_dispatch:
    inputs:
      ref:
        description: the repository ref to build
        required: true
        default: main

  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

# Cancel previous runs of the same branch
concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.run_id }}'
  cancel-in-progress: true

env:
  AGDAHTMLFLAGS: --only-scope-checking --html --html-highlight=code --html-dir=docs --css=docs/Agda.css
  AGDA: agda

jobs:
  typecheck:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macOS-latest , ubuntu-latest ]
        agda: [ '2.6.3' ]
    steps:
      - name: Checkout our repository
        uses: actions/checkout@v3
        with:
          path: main
      - name: Setup Agda
        uses: wenkokke/setup-agda@v2.0.0
        with:
          agda-version: ${{ matrix.agda }}

      - uses: actions/cache/restore@v3
        id: cache-agda-formalisation
        name: Restore Agda formalisation cache
        with:
          path: main/_build
          key: ${{ runner.os }}-check-${{ github.ref }}-${{ matrix.agda }}-${{ hashFiles('main/src/**') }}
          restore-keys: |
            ${{ runner.os }}-check-${{ github.ref }}-${{ matrix.agda }}-
            ${{ runner.os }}-check-refs/heads/master-${{ matrix.agda }}-

      - name: Typecheck the whole formalisation
        run: |
          cd main
          make check

      - name: Save Agda build cache
        uses: actions/cache/save@v3
        with:
          path: main/_build
          key: '${{ steps.cache-agda-formalisation.outputs.cache-primary-key }}'

  check-docs-gen:
    runs-on: macOS-latest
    strategy:
      matrix:
        agda: [ '2.6.3' ]
    needs: typecheck
    steps:
      - name: Checkout our repository
        uses: actions/checkout@v3
        with:
          path: main
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.0.1'

      - name: Setup Agda
        uses: wenkokke/setup-agda@v2.0.0
        with:
          agda-version: ${{ matrix.agda }}

      - uses: actions/cache/restore@v3
        id: cache-agda-formalisation
        name: Restore Agda formalisation cache
        with:
          path: main/_build
          key: ${{ runner.os }}-check-${{ github.ref }}-${{ matrix.agda }}-${{ hashFiles('main/src/**') }}
          restore-keys: |
            ${{ runner.os }}-check-${{ github.ref }}-${{ matrix.agda }}-
            ${{ runner.os }}-check-refs/heads/master-${{ matrix.agda }}-

      - name: Generate HTML to check no errors are raised
        id: gen-html
        run: |
          cd main
          make agda-html

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
